# Preventive Care Compliance and Gap Analysis

In [104]:
# Import Libraries
import pandas as pd
# For Postgres Database Connection
## psycopg2 - Work as adapter
import psycopg2 
from sqlalchemy import create_engine

In [105]:
# standardize_patient_id
def standardize_id(x, prefix_id):
    try:
        if pd.isna(x):
            return None
        return f'{prefix_id}{int(x):04d}'
    except:
        return None

In [106]:
# Age-Group IDentification
def age_group(age):
    if age <= 18:
        return '0-18'
    elif age <= 35:
        return '19-35'
    elif age <= 59:
        return '36-59'
    else:
        return '60+'

### Patient Data Analysis

In [107]:
df_patients = pd.read_excel('../Rawdata/patients.xlsx')

In [108]:
df_patients.head()

,patient_id,first_name,last_name,gender,date_of_birth,age,city,state,registration_date,is_active
0,1,Patricia,Smith,Female,2009-10-06,16,Noblesville,IN,2017-05-10,Yes
1,2,Robert,Brown,Male,1959-10-05,66,Fort Wayne,IN,2025-04-30,No
2,3,Mary,Smith,Male,1975-11-24,50,Noblesville,IN,2016-04-11,Yes
3,4,Thomas,Martin,Male,1957-02-13,69,Fort Wayne,IN,2024-06-06,Yes
4,5,Karen,Wilson,Male,1976-02-11,50,Fishers,IN,2022-12-29,No

In [109]:
df_patients.tail()

,patient_id,first_name,last_name,gender,date_of_birth,age,city,state,registration_date,is_active
5995,5996,David,Thomas,Male,1958-02-23,68,Bloomington,IN,2015-08-03,Yes
5996,5997,Mary,Martin,Male,1959-10-15,66,Evansville,IN,2016-04-09,Yes
5997,5998,Mary,Jackson,Female,1962-02-08,64,Bloomington,IN,2021-06-30,Yes
5998,5999,Jessica,Lopez,Female,1989-04-07,37,Carmel,IN,2016-08-14,Yes
5999,6000,Linda,Martinez,Female,1973-06-03,52,Carmel,IN,2017-06-02,Yes

In [110]:
df_patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         6000 non-null   int64
 1   first_name         6000 non-null   str
 2   last_name          6000 non-null   str
 3   gender             6000 non-null   str
 4   date_of_birth      6000 non-null   datetime64[us]
 5   age                6000 non-null   int64
 6   city               6000 non-null   str
 7   state              6000 non-null   str
 8   registration_date  6000 non-null   datetime64[us]
 9   is_active          6000 non-null   str
dtypes: datetime64[us](2), int64(2), str(6)
memory usage: 468.9 KB

In [111]:
# Standardizing patient_id
df_patients['patient_id'] = df_patients['patient_id'].apply(lambda x: standardize_id(x, 'P'))

In [112]:
df_patients['age_group'] = df_patients['age'].apply(age_group)

In [113]:
df_patients.tail()

,patient_id,first_name,last_name,gender,date_of_birth,age,city,state,registration_date,is_active,age_group
5995,P5996,David,Thomas,Male,1958-02-23,68,Bloomington,IN,2015-08-03,Yes,60+
5996,P5997,Mary,Martin,Male,1959-10-15,66,Evansville,IN,2016-04-09,Yes,60+
5997,P5998,Mary,Jackson,Female,1962-02-08,64,Bloomington,IN,2021-06-30,Yes,60+
5998,P5999,Jessica,Lopez,Female,1989-04-07,37,Carmel,IN,2016-08-14,Yes,36-59
5999,P6000,Linda,Martinez,Female,1973-06-03,52,Carmel,IN,2017-06-02,Yes,36-59

### Patients Care Data Analysis

In [114]:
df_patient_care = pd.read_excel('../Rawdata/patient_care_records.xlsx')

In [115]:
df_patient_care.head()

,record_id,patient_id,care_id,date_completed,status,due_date,is_overdue,completion_source,provider_name,notes
0,1,4304,3,NaT,Due,2026-06-24,No,Hospital,Dr. Brown,Due
1,2,2994,11,2025-12-23,Completed,2026-01-07,No,Clinic,Dr. Johnson,Completed
2,3,5545,12,2025-04-02,Completed,2025-04-18,No,Phone,Dr. Brown,Completed
3,4,262,4,NaT,Overdue,2025-01-01,Yes,Portal,Dr. Smith,Overdue
4,5,2132,8,NaT,Overdue,2026-07-11,Yes,Portal,Dr. Smith,Overdue

In [116]:
df_patient_care.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   record_id          30000 non-null  int64
 1   patient_id         30000 non-null  int64
 2   care_id            30000 non-null  int64
 3   date_completed     13442 non-null  datetime64[us]
 4   status             30000 non-null  str
 5   due_date           30000 non-null  datetime64[us]
 6   is_overdue         30000 non-null  str
 7   completion_source  30000 non-null  str
 8   provider_name      30000 non-null  str
 9   notes              30000 non-null  str
dtypes: datetime64[us](2), int64(3), str(5)
memory usage: 2.3 MB

In [117]:
# Standardizing id's
df_patient_care['record_id'] = df_patient_care['record_id'].apply(lambda x: standardize_id(x, 'R'))
df_patient_care['patient_id'] = df_patient_care['patient_id'].apply(lambda x: standardize_id(x, 'P'))
df_patient_care['care_id'] = df_patient_care['care_id'].apply(lambda x: standardize_id(x, 'C'))

In [118]:
df_patient_care['due_date'] = pd.to_datetime(df_patient_care['due_date'])

df_patient_care['month_start'] = df_patient_care['due_date'].dt.to_period('M').dt.to_timestamp()

In [119]:
df_patient_care.head()

,record_id,patient_id,care_id,date_completed,status,due_date,is_overdue,completion_source,provider_name,notes,month_start
0,R0001,P4304,C0003,NaT,Due,2026-06-24,No,Hospital,Dr. Brown,Due,2026-06-01
1,R0002,P2994,C0011,2025-12-23,Completed,2026-01-07,No,Clinic,Dr. Johnson,Completed,2026-01-01
2,R0003,P5545,C0012,2025-04-02,Completed,2025-04-18,No,Phone,Dr. Brown,Completed,2025-04-01
3,R0004,P0262,C0004,NaT,Overdue,2025-01-01,Yes,Portal,Dr. Smith,Overdue,2025-01-01
4,R0005,P2132,C0008,NaT,Overdue,2026-07-11,Yes,Portal,Dr. Smith,Overdue,2026-07-01

In [120]:
df_patient_care.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   record_id          30000 non-null  str
 1   patient_id         30000 non-null  str
 2   care_id            30000 non-null  str
 3   date_completed     13442 non-null  datetime64[us]
 4   status             30000 non-null  str
 5   due_date           30000 non-null  datetime64[us]
 6   is_overdue         30000 non-null  str
 7   completion_source  30000 non-null  str
 8   provider_name      30000 non-null  str
 9   notes              30000 non-null  str
 10  month_start        30000 non-null  datetime64[us]
dtypes: datetime64[us](3), str(8)
memory usage: 2.5 MB

### Preventive Care Analysis

In [121]:
df_preventive_care = pd.read_excel('../Rawdata/preventive_care.xlsx')

In [122]:
df_preventive_care.head()

,care_id,care_name,care_category,min_age,max_age,gender,frequency,recommended_interval_days,is_mandatory,guideline_source
0,1,Flu Vaccine,Vaccination,18,100,All,Yearly,365,Yes,CDC
1,2,COVID-19 Vaccine,Vaccination,18,100,All,Yearly,365,Yes,CDC
2,3,Hepatitis B Vaccine,Vaccination,0,60,All,Once,0,Yes,CDC
3,4,Tetanus Booster,Vaccination,18,100,All,Every 10 years,3650,Yes,CDC
4,5,HPV Vaccine,Vaccination,9,26,All,Once,0,Yes,CDC

In [123]:
df_preventive_care.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   care_id                    15 non-null     int64
 1   care_name                  15 non-null     str
 2   care_category              15 non-null     str
 3   min_age                    15 non-null     int64
 4   max_age                    15 non-null     int64
 5   gender                     15 non-null     str
 6   frequency                  15 non-null     str
 7   recommended_interval_days  15 non-null     int64
 8   is_mandatory               15 non-null     str
 9   guideline_source           15 non-null     str
dtypes: int64(4), str(6)
memory usage: 1.3 KB

In [124]:
# Standardizing care_id
df_preventive_care['care_id'] = df_preventive_care['care_id'].apply(lambda x: standardize_id(x, 'C'))

In [125]:
df_preventive_care.tail()

,care_id,care_name,care_category,min_age,max_age,gender,frequency,recommended_interval_days,is_mandatory,guideline_source
10,C0011,Blood Pressure Check,Routine Check,18,100,All,Yearly,365,Yes,WHO
11,C0012,Eye Exam,Routine Check,40,100,All,Every 2 years,730,No,WHO
12,C0013,Dental Checkup,Routine Check,5,100,All,Every 6 months,180,No,WHO
13,C0014,Bone Density Test,Screening,65,100,Female,Every 2 years,730,Yes,USPSTF
14,C0015,Prostate Screening,Screening,50,75,Male,Yearly,365,No,USPSTF

In [126]:
df_preventive_care

,care_id,care_name,care_category,min_age,max_age,gender,frequency,recommended_interval_days,is_mandatory,guideline_source
0,C0001,Flu Vaccine,Vaccination,18,100,All,Yearly,365,Yes,CDC
1,C0002,COVID-19 Vaccine,Vaccination,18,100,All,Yearly,365,Yes,CDC
2,C0003,Hepatitis B Vaccine,Vaccination,0,60,All,Once,0,Yes,CDC
3,C0004,Tetanus Booster,Vaccination,18,100,All,Every 10 years,3650,Yes,CDC
4,C0005,HPV Vaccine,Vaccination,9,26,All,Once,0,Yes,CDC
5,C0006,Mammogram,Screening,40,70,Female,Yearly,365,Yes,USPSTF
6,C0007,Pap Smear,Screening,21,65,Female,Every 3 years,1095,Yes,USPSTF
7,C0008,Colonoscopy,Screening,50,75,All,Every 10 years,3650,Yes,USPSTF
8,C0009,Diabetes Screening,Screening,30,100,All,Yearly,365,Yes,WHO
9,C0010,Cholesterol Test,Screening,20,100,All,Every 5 years,1825,No,WHO
10,C0011,Blood Pressure Check,Routine Check,18,100,All,Yearly,365,Yes,WHO
11,C0012,Eye Exam,Routine Check,40,100,All,Every 2 years,730,No,WHO
12,C0013,Dental Checkup,Routine Check,5,100,All,Every 6 months,180,No,WHO
13,C0014,Bone Density Test,Screening,65,100,Female,Every 2 years,730,Yes,USPSTF
14,C0015,Prostate Screening,Screening,50,75,Male,Yearly,365,No,USPSTF

In [127]:
# Postgres Connection

host = 'localhost'
port = 5432
user = 'postgres'   
password = '1108'

In [128]:
# Download the clean CSV files
df_patients.to_csv('../Rawdata/patients_clean_data.csv',index = False)
df_patient_care.to_csv('../Rawdata/patients_care_clean_data.csv',index = False)
df_preventive_care.to_csv('../Rawdata/preventive_care_clean_data.csv',index = False)

In [129]:
print("Patients:", df_patients.shape)
print("Patient Care:",df_patient_care.shape)
print("Preventive Care:",df_preventive_care.shape)

Patients: (6000, 11)
Patient Care: (30000, 11)
Preventive Care: (15, 10)

In [130]:
help(create_engine)

Help on function create_engine in module sqlalchemy.engine.create:

create_engine(url: 'Union[str, _url.URL]', **kwargs: 'Any') -> 'Engine'
    Create a new :class:`_engine.Engine` instance.

    The standard calling form is to send the :ref:`URL <database_urls>` as the
    first positional argument, usually a string
    that indicates database dialect and connection arguments::

        engine = create_engine("postgresql+psycopg2://scott:tiger@localhost/test")

    .. note::

        Please review :ref:`database_urls` for general guidelines in composing
        URL strings.  In particular, special characters, such as those often
        part of passwords, must be URL encoded to be properly parsed.

    Additional keyword arguments may then follow it which
    establish various options on the resulting :class:`_engine.Engine`
    and its underlying :class:`.Dialect` and :class:`_pool.Pool`
    constructs::

        engine = create_engine(
            "mysql+mysqldb://scott:tiger@hostname/dbname",
            pool_recycle=3600,
            echo=True,
        )

    The string form of the URL is
    ``dialect[+driver]://user:password@host/dbname[?key=value..]``, where
    ``dialect`` is a database name such as ``mysql``, ``oracle``,
    ``postgresql``, etc., and ``driver`` the name of a DBAPI, such as
    ``psycopg2``, ``pyodbc``, ``cx_oracle``, etc.  Alternatively,
    the URL can be an instance of :class:`~sqlalchemy.engine.url.URL`.

    ``**kwargs`` takes a wide variety of options which are routed
    towards their appropriate components.  Arguments may be specific to
    the :class:`_engine.Engine`, the underlying :class:`.Dialect`,
    as well as the
    :class:`_pool.Pool`.  Specific dialects also accept keyword arguments that
    are unique to that dialect.   Here, we describe the parameters
    that are common to most :func:`_sa.create_engine()` usage.

    Once established, the newly resulting :class:`_engine.Engine` will
    request a connection from the underlying :class:`_pool.Pool` once
    :meth:`_engine.Engine.connect` is called, or a method which depends on it
    such as :meth:`_engine.Engine.execute` is invoked.   The
    :class:`_pool.Pool` in turn
    will establish the first actual DBAPI connection when this request
    is received.   The :func:`_sa.create_engine` call itself does **not**
    establish any actual DBAPI connections directly.

    .. seealso::

        :doc:`/core/engines`

        :doc:`/dialects/index`

        :ref:`connections_toplevel`

    :param connect_args: a dictionary of options which will be
        passed directly to the DBAPI's ``connect()`` method as
        additional keyword arguments.  See the example
        at :ref:`custom_dbapi_args`.

    :param creator: a callable which returns a DBAPI connection.
        This creation function will be passed to the underlying
        connection pool and will be used to create all new database
        connections. Usage of this function causes connection
        parameters specified in the URL argument to be bypassed.

        This hook is not as flexible as the newer
        :meth:`_events.DialectEvents.do_connect` hook which allows complete
        control over how a connection is made to the database, given the full
        set of URL arguments and state beforehand.

        .. seealso::

            :meth:`_events.DialectEvents.do_connect` - event hook that allows
            full control over DBAPI connection mechanics.

            :ref:`custom_dbapi_args`

    :param echo=False: if True, the Engine will log all statements
        as well as a ``repr()`` of their parameter lists to the default log
        handler, which defaults to ``sys.stdout`` for output.   If set to the
        string ``"debug"``, result rows will be printed to the standard output
        as well. The ``echo`` attribute of ``Engine`` can be modified at any
        time to turn logging on and off; direct control of logging is also
        available using the standard Python ``logging`` module.

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.


    :param echo_pool=False: if True, the connection pool will log
        informational output such as when connections are invalidated
        as well as when connections are recycled to the default log handler,
        which defaults to ``sys.stdout`` for output.   If set to the string
        ``"debug"``, the logging will include pool checkouts and checkins.
        Direct control of logging is also available using the standard Python
        ``logging`` module.

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.


    :param empty_in_strategy:   No longer used; SQLAlchemy now uses
        "empty set" behavior for IN in all cases.

        .. deprecated:: 1.4 The :paramref:`_sa.create_engine.empty_in_strategy` keyword is deprecated, and no longer has any effect.  All IN expressions are now rendered using the "expanding parameter" strategy which renders a set of boundexpressions, or an "empty set" SELECT, at statement executiontime.



    :param enable_from_linting: defaults to True.  Will emit a warning
        if a given SELECT statement is found to have un-linked FROM elements
        which would cause a cartesian product.

        .. versionadded:: 1.4

        .. seealso::

            :ref:`change_4737`

    :param execution_options: Dictionary execution options which will
        be applied to all connections.  See
        :meth:`~sqlalchemy.engine.Connection.execution_options`

    :param future: Use the 2.0 style :class:`_engine.Engine` and
        :class:`_engine.Connection` API.

        As of SQLAlchemy 2.0, this parameter is present for backwards
        compatibility only and must remain at its default value of ``True``.

        The :paramref:`_sa.create_engine.future` parameter will be
        deprecated in a subsequent 2.x release and eventually removed.

        .. versionadded:: 1.4

        .. versionchanged:: 2.0 All :class:`_engine.Engine` objects are
           "future" style engines and there is no longer a ``future=False``
           mode of operation.

        .. seealso::

            :ref:`migration_20_toplevel`

    :param hide_parameters: Boolean, when set to True, SQL statement parameters
        will not be displayed in INFO logging nor will they be formatted into
        the string representation of :class:`.StatementError` objects.

        .. versionadded:: 1.3.8

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.

    :param implicit_returning=True:  Legacy parameter that may only be set
        to True. In SQLAlchemy 2.0, this parameter does nothing. In order to
        disable "implicit returning" for statements invoked by the ORM,
        configure this on a per-table basis using the
        :paramref:`.Table.implicit_returning` parameter.


    :param insertmanyvalues_page_size: number of rows to format into an
     INSERT statement when the statement uses "insertmanyvalues" mode, which is
     a paged form of bulk insert that is used for many backends when using
     :term:`executemany` execution typically in conjunction with RETURNING.
     Defaults to 1000, but may also be subject to dialect-specific limiting
     factors which may override this value on a per-statement basis.

     .. versionadded:: 2.0

     .. seealso::

        :ref:`engine_insertmanyvalues`

        :ref:`engine_insertmanyvalues_page_size`

        :paramref:`_engine.Connection.execution_options.insertmanyvalues_page_size`

    :param isolation_level: optional string name of an isolation level
        which will be set on all new connections unconditionally.
        Isolation levels are typically some subset of the string names
        ``"SERIALIZABLE"``, ``"REPEATABLE READ"``,
        ``"READ COMMITTED"``, ``"READ UNCOMMITTED"`` and ``"AUTOCOMMIT"``
        based on backend.

        The :paramref:`_sa.create_engine.isolation_level` parameter is
        in contrast to the
        :paramref:`.Connection.execution_options.isolation_level`
        execution option, which may be set on an individual
        :class:`.Connection`, as well as the same parameter passed to
        :meth:`.Engine.execution_options`, where it may be used to create
        multiple engines with different isolation levels that share a common
        connection pool and dialect.

        .. versionchanged:: 2.0 The
           :paramref:`_sa.create_engine.isolation_level`
           parameter has been generalized to work on all dialects which support
           the concept of isolation level, and is provided as a more succinct,
           up front configuration switch in contrast to the execution option
           which is more of an ad-hoc programmatic option.

        .. seealso::

            :ref:`dbapi_autocommit`

    :param json_deserializer: for dialects that support the
        :class:`_types.JSON`
        datatype, this is a Python callable that will convert a JSON string
        to a Python object.  By default, the Python ``json.loads`` function is
        used.

        .. versionchanged:: 1.3.7  The SQLite dialect renamed this from
           ``_json_deserializer``.

    :param json_serializer: for dialects that support the :class:`_types.JSON`
        datatype, this is a Python callable that will render a given object
        as JSON.   By default, the Python ``json.dumps`` function is used.

        .. versionchanged:: 1.3.7  The SQLite dialect renamed this from
           ``_json_serializer``.


    :param label_length=None: optional integer value which limits
        the size of dynamically generated column labels to that many
        characters. If less than 6, labels are generated as
        "_(counter)". If ``None``, the value of
        ``dialect.max_identifier_length``, which may be affected via the
        :paramref:`_sa.create_engine.max_identifier_length` parameter,
        is used instead.   The value of
        :paramref:`_sa.create_engine.label_length`
        may not be larger than that of
        :paramref:`_sa.create_engine.max_identfier_length`.

        .. seealso::

            :paramref:`_sa.create_engine.max_identifier_length`

    :param logging_name:  String identifier which will be used within
        the "name" field of logging records generated within the
        "sqlalchemy.engine" logger. Defaults to a hexstring of the
        object's id.

        .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.

            :paramref:`_engine.Connection.execution_options.logging_token`

    :param max_identifier_length: integer; override the max_identifier_length
        determined by the dialect.  if ``None`` or zero, has no effect.  This
        is the database's configured maximum number of characters that may be
        used in a SQL identifier such as a table name, column name, or label
        name. All dialects determine this value automatically, however in the
        case of a new database version for which this value has changed but
        SQLAlchemy's dialect has not been adjusted, the value may be passed
        here.

        .. versionadded:: 1.3.9

        .. seealso::

            :paramref:`_sa.create_engine.label_length`

    :param max_overflow=10: the number of connections to allow in
        connection pool "overflow", that is connections that can be
        opened above and beyond the pool_size setting, which defaults
        to five. this is only used with :class:`~sqlalchemy.pool.QueuePool`.

    :param module=None: reference to a Python module object (the module
        itself, not its string name).  Specifies an alternate DBAPI module to
        be used by the engine's dialect.  Each sub-dialect references a
        specific DBAPI which will be imported before first connect.  This
        parameter causes the import to be bypassed, and the given module to
        be used instead. Can be used for testing of DBAPIs as well as to
        inject "mock" DBAPI implementations into the :class:`_engine.Engine`.

    :param paramstyle=None: The `paramstyle <https://legacy.python.org/dev/peps/pep-0249/#paramstyle>`_
        to use when rendering bound parameters.  This style defaults to the
        one recommended by the DBAPI itself, which is retrieved from the
        ``.paramstyle`` attribute of the DBAPI.  However, most DBAPIs accept
        more than one paramstyle, and in particular it may be desirable
        to change a "named" paramstyle into a "positional" one, or vice versa.
        When this attribute is passed, it should be one of the values
        ``"qmark"``, ``"numeric"``, ``"named"``, ``"format"`` or
        ``"pyformat"``, and should correspond to a parameter style known
        to be supported by the DBAPI in use.

    :param pool=None: an already-constructed instance of
        :class:`~sqlalchemy.pool.Pool`, such as a
        :class:`~sqlalchemy.pool.QueuePool` instance. If non-None, this
        pool will be used directly as the underlying connection pool
        for the engine, bypassing whatever connection parameters are
        present in the URL argument. For information on constructing
        connection pools manually, see :ref:`pooling_toplevel`.

    :param poolclass=None: a :class:`~sqlalchemy.pool.Pool`
        subclass, which will be used to create a connection pool
        instance using the connection parameters given in the URL. Note
        this differs from ``pool`` in that you don't actually
        instantiate the pool in this case, you just indicate what type
        of pool to be used.

    :param pool_logging_name:  String identifier which will be used within
       the "name" field of logging records generated within the
       "sqlalchemy.pool" logger. Defaults to a hexstring of the object's
       id.

       .. seealso::

            :ref:`dbengine_logging` - further detail on how to configure
            logging.

    :param pool_pre_ping: boolean, if True will enable the connection pool
        "pre-ping" feature that tests connections for liveness upon
        each checkout.

        .. versionadded:: 1.2

        .. seealso::

            :ref:`pool_disconnects_pessimistic`

    :param pool_size=5: the number of connections to keep open
        inside the connection pool. This used with
        :class:`~sqlalchemy.pool.QueuePool` as
        well as :class:`~sqlalchemy.pool.SingletonThreadPool`.  With
        :class:`~sqlalchemy.pool.QueuePool`, a ``pool_size`` setting
        of 0 indicates no limit; to disable pooling, set ``poolclass`` to
        :class:`~sqlalchemy.pool.NullPool` instead.

    :param pool_recycle=-1: this setting causes the pool to recycle
        connections after the given number of seconds has passed. It
        defaults to -1, or no timeout. For example, setting to 3600
        means connections will be recycled after one hour. Note that
        MySQL in particular will disconnect automatically if no
        activity is detected on a connection for eight hours (although
        this is configurable with the MySQLDB connection itself and the
        server configuration as well).

        .. seealso::

            :ref:`pool_setting_recycle`

    :param pool_reset_on_return='rollback': set the
        :paramref:`_pool.Pool.reset_on_return` parameter of the underlying
        :class:`_pool.Pool` object, which can be set to the values
        ``"rollback"``, ``"commit"``, or ``None``.

        .. seealso::

            :ref:`pool_reset_on_return`

            :ref:`dbapi_autocommit_skip_rollback` - a more modern approach
            to using connections with no transactional instructions

    :param pool_timeout=30: number of seconds to wait before giving
        up on getting a connection from the pool. This is only used
        with :class:`~sqlalchemy.pool.QueuePool`. This can be a float but is
        subject to the limitations of Python time functions which may not be
        reliable in the tens of milliseconds.

        .. note: don't use 30.0 above, it seems to break with the :param tag

    :param pool_use_lifo=False: use LIFO (last-in-first-out) when retrieving
        connections from :class:`.QueuePool` instead of FIFO
        (first-in-first-out). Using LIFO, a server-side timeout scheme can
        reduce the number of connections used during non- peak   periods of
        use.   When planning for server-side timeouts, ensure that a recycle or
        pre-ping strategy is in use to gracefully   handle stale connections.

          .. versionadded:: 1.3

          .. seealso::

            :ref:`pool_use_lifo`

            :ref:`pool_disconnects`

    :param plugins: string list of plugin names to load.  See
        :class:`.CreateEnginePlugin` for background.

        .. versionadded:: 1.2.3

    :param query_cache_size: size of the cache used to cache the SQL string
     form of queries.  Set to zero to disable caching.

     The cache is pruned of its least recently used items when its size reaches
     N * 1.5.  Defaults to 500, meaning the cache will always store at least
     500 SQL statements when filled, and will grow up to 750 items at which
     point it is pruned back down to 500 by removing the 250 least recently
     used items.

     Caching is accomplished on a per-statement basis by generating a
     cache key that represents the statement's structure, then generating
     string SQL for the current dialect only if that key is not present
     in the cache.   All statements support caching, however some features
     such as an INSERT with a large set of parameters will intentionally
     bypass the cache.   SQL logging will indicate statistics for each
     statement whether or not it were pull from the cache.

     .. note:: some ORM functions related to unit-of-work persistence as well
        as some attribute loading strategies will make use of individual
        per-mapper caches outside of the main cache.


     .. seealso::

        :ref:`sql_caching`

     .. versionadded:: 1.4

    :param skip_autocommit_rollback: When True, the dialect will
       unconditionally skip all calls to the DBAPI ``connection.rollback()``
       method if the DBAPI connection is confirmed to be in "autocommit" mode.
       The availability of this feature is dialect specific; if not available,
       a ``NotImplementedError`` is raised by the dialect when rollback occurs.

       .. seealso::

            :ref:`dbapi_autocommit_skip_rollback`

       .. versionadded:: 2.0.43

    :param use_insertmanyvalues: True by default, use the "insertmanyvalues"
     execution style for INSERT..RETURNING statements by default.

     .. versionadded:: 2.0

     .. seealso::

        :ref:`engine_insertmanyvalues`

In [131]:
# Postgres SQL
engine_postgres = create_engine("postgresql+psycopg2://postgres:1108@localhost:5432/caretrack")

try:
    engine_postgres
    print("Connection Successed to PSQL")
except:
    print("Unable to Connect")

Connection Successed to PSQL

In [132]:
df_patients.to_sql(name = 'patients', con=engine_postgres, if_exists='replace',index=False)

1000

In [133]:
df_patient_care.to_sql(name = 'patient_care', con=engine_postgres, if_exists='replace',index=False)

1000

In [134]:
df_preventive_care.to_sql(name = 'preventive_care', con=engine_postgres, if_exists='replace',index=False)

15

In [135]:
print("Patients:", df_patients.shape)
print("Patient Care:",df_patient_care.shape)
print("Preventive Care:",df_preventive_care.shape)

Patients: (6000, 11)
Patient Care: (30000, 11)
Preventive Care: (15, 10)